apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      # NAT-ing usually causes issues when load-testing
      hostNetwork: true
      containers:
        - image: "{{ $.Values.image.repository }}:{{ default $.Chart.AppVersion $.Values.image.tag }}"
          name: tsh-bench
          command:
            - tsh 
            - "--proxy={{ .Values.proxyServer }}"
            - "-i"
            - "/mnt/identity.pem"
            - "bench"
            - "sessions"
            - "--max={{.Values.sessionsPerAgent}}"
            - "root"
            {{- toYaml .Values.command | nindent 12 }}
          volumeMounts:
            - mountPath: /mnt
              name: identity
              readOnly: true
          resources: {{- toYaml $.Values.resources | nindent 12 }}
        {{- if .Values.webSessions }}
        - image: "{{ $.Values.image.repository }}:{{ default $.Chart.AppVersion $.Values.image.tag }}"
          name: tsh-bench-web
          command:
            - tsh 
            - "--proxy={{ .Values.proxyServer }}"
            - "-i"
            - "/mnt/identity.pem"
            - "bench"
            - "sessions"
            - "--max={{.Values.sessionsPerAgent}}"
            - "--web"
            {{- toYaml .Values.command | nindent 12 }}
          volumeMounts:
            - mountPath: /mnt
              name: identity
              readOnly: true
          resources: {{- toYaml $.Values.resources | nindent 12 }}
        {{- end }}
      volumes:
        - secret:
            secretName: {{ .Release.Name }}
            optional: false
          name: identity
      {{- if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8}}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{ toYaml .Values.affinity | nindent 8}}
      {{- end }}
