version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: "sunday"
      time: "09:00" # 9am UTC
    ignore:
      # Deprecated APIs, requires manual changes.
      # TODO(xacrimon): Update Firestore and solve deprecations.
      - dependency-name: cloud.google.com/go/firestore
      # Depends on newer Firestore version.
      - dependency-name: cloud.google.com/go/iam
      - dependency-name: cloud.google.com/go/kms
      - dependency-name: github.com/fsouza/fake-gcs-server
      - dependency-name: google.golang.org/api
      - dependency-name: google.golang.org/genproto
      # Breaks backwards compatibility
      - dependency-name: github.com/gravitational/ttlmap
      # TODO(greedy52): Update mongo-driver and fix API changes.
      - dependency-name: go.mongodb.org/mongo-driver
      # Must be kept in-sync with libbpf
      - dependency-name: github.com/aquasecurity/libbpfgo
      # Forked/replaced dependencies
      - dependency-name: github.com/coreos/go-oidc
      - dependency-name: github.com/denisenkom/go-mssqldb
      - dependency-name: github.com/go-mysql-org/go-mysql
      - dependency-name: github.com/go-redis/redis/v9
      - dependency-name: github.com/gogo/protobuf
      - dependency-name: github.com/julienschmidt/httprouter
      - dependency-name: github.com/keys-pub/go-libfido2
      - dependency-name: github.com/pkg/sftp
      - dependency-name: github.com/sirupsen/logrus
      - dependency-name: github.com/vulcand/predicate
      - dependency-name: golang.org/x/crypto
    open-pull-requests-limit: 10
    reviewers:
      - codingllama
      - rosstimothy
      - zmb3

  - package-ecosystem: gomod
    directory: "/api"
    schedule:
      interval: weekly
      day: "sunday"
      time: "09:00" # 9am UTC
    ignore:
      # TODO(tross): Update after Firestore is updated
      - dependency-name: google.golang.org/genproto
      # Forked/replaced dependencies
      - dependency-name: golang.org/x/crypto
    open-pull-requests-limit: 10
    reviewers:
      - codingllama
      - rosstimothy
      - zmb3

  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      day: "sunday"
      time: "09:00" # 9am UTC
    open-pull-requests-limit: 10
    reviewers:
      - codingllama
      - rosstimothy
      - zmb3

  - package-ecosystem: cargo
    directory: "/lib/srv/desktop/rdp/rdpclient"
    schedule:
      interval: weekly
      day: "sunday"
      time: "09:00" # 9am UTC
    open-pull-requests-limit: 10
    reviewers:
      - codingllama
      - rosstimothy
      - zmb3
