version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      # Deprecated APIs, requires manual changes.
      # TODO(xacrimon): Update Firestore and solve deprecations.
      - dependency-name: cloud.google.com/go/firestore
      # Breaks backwards compatibility
      - dependency-name: github.com/gravitational/ttlmap
      # Must be kept in-sync with libbpf
      - dependency-name: github.com/aquasecurity/libbpfgo
      # Forked/replaced dependencies
      - dependency-name: github.com/coreos/go-oidc v2.1.0+incompatible
      - dependency-name: github.com/denisenkom/go-mssqldb v0.11.0
      - dependency-name: github.com/go-mysql-org/go-mysql v1.5.0
      - dependency-name: github.com/go-redis/redis/v8 v8.11.4
      - dependency-name: github.com/gogo/protobuf v1.3.2
      - dependency-name: github.com/julienschmidt/httprouter v1.3.0
      - dependency-name: github.com/keys-pub/go-libfido2 v1.5.3-0.20220306005615-8ab03fb1ec27
      - dependency-name: github.com/pkg/sftp v1.13.5
      - dependency-name: github.com/sirupsen/logrus v1.9.0
      - dependency-name: github.com/vulcand/predicate v1.2.0
    open-pull-requests-limit: 10
    reviewers:
      - codingllama
      - rosstimothy
      - zmb3

  - package-ecosystem: gomod
    directory: "/api"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - codingllama
      - rosstimothy
      - zmb3

  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - codingllama
      - rosstimothy
      - zmb3

  - package-ecosystem: cargo
    directory: "/lib/srv/desktop/rdp/rdpclient"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - codingllama
      - rosstimothy
      - zmb3
