replicaCount: 1
agentsPerPod: 10
proxyServer: ""
authServer: ""

minReadySeconds: 0

image:
  repository: public.ecr.aws/gravitational/teleport
  pullPolicy: IfNotPresent
  tag: ""

serviceAccount:
  create: true

joinParams:
  # the kubernetes join method is not currently suited for joining a large amoubt of nodes in a short time
  method: token
  # DO NOT USE THIS IN PRODUCTION
  token_name: qwertyuiop

# Applied par agent (not per-pod)
resources:
  limits:
    memory: 150Mi
  requests:
    cpu: 20m
    memory: 150Mi

tolerations: []

affinity: {}
