name: Run difftest
description: Runs difftest
inputs:
  flags:
    description: difftest flags
    required: true

  target:
    description: make target
    required: true

  attempts:
    description: Number of runs
    required: false
    default: 30

  bin:
    description: difftest binary location
    required: false
    default: ${GITHUB_WORKSPACE}/build.assets/tooling/bin/difftest

  path:
    description: difftest path
    required: false
    default: ${GITHUB_WORKSPACE}
        
runs:
  using: "composite"
  steps:
    - name: Build
      shell: bash
      run: make ${{ inputs.bin }}

    - name: Show
      id: diffs
      shell: bash
      run: |
        ${{ inputs.bin }} diff --path ${{ inputs.path }} --branch remotes/origin/${GITHUB_BASE_REF} ${{ inputs.flags }}
        echo "subject=$(${{ inputs.bin }} test --path ${{ inputs.path }} --branch remotes/origin/${GITHUB_BASE_REF} ${{ inputs.flags }} -u -d)" > $GITHUB_OUTPUT

    - name: Run
      shell: bash
      run: SUBJECT='${{ steps.diffs.outputs.subject }}' ADDFLAGS='-count ${{ inputs.attempts }}' make ${{ inputs.target }}
