{{- $auth := mustMergeOverwrite .Values .Values.auth -}}
{{- if $auth.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "teleport-cluster.auth.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- if $auth.annotations.serviceAccount }}
  annotations:
{{- toYaml $auth.annotations.serviceAccount | nindent 4 }}
{{- end -}}
{{- end }}
