# This resource is only required for pre-v12 `teleport-cluster` Helm chart
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: teleport
  namespace: teleport
spec:
  jobLabel: app
  namespaceSelector:
    matchNames:
      - teleport
  selector:
    matchLabels:
      app: teleport
  podMetricsEndpoints:
    - port: diag
      path: /metrics
