replicaCount: 1
sessionsPerAgent: 1000
proxyServer: ""

minReadySeconds: 0

# Web sessions is untested
# In theory it should work, but you need to find a way to pass the OTP challenge without an interactive terminal
webSessions: false

command:
  - "sh"
  - "-c"
  - "while ls; do sleep 5; done"

image:
  repository: public.ecr.aws/gravitational/teleport
  pullPolicy: IfNotPresent
  # This tag contains `tsh bench sessions`
  tag: "10.1.4-bench.2"

# Applied par agent
resources:
  limits:
    memory: 3Gi
  requests:
    cpu: "4"
    memory: 3Gi

tolerations: []

affinity: {}
