timeout: 30m

options:
  machineType: E2_HIGHCPU_32

  # This build needs to run in environments where the _GITHUB_DEPLOY_KEY_SRC
  # substitution is defined, but also environments where it isn't. The
  # ALLOW_LOOSE option disables GCB's strict checking of substitution usage,
  # so that the build will still run if _GITHUB_DEPLOY_KEY_SRC is not defined.
  substitution_option: ALLOW_LOOSE

steps:
  # Run the unit tests. Actual content of this job depends on the changes
  # detected in the PR
  - name: public.ecr.aws/gravitational/teleport-buildbox:teleport12
    id: run-tests
    dir: /workspace/.cloudbuild/scripts
    entrypoint: bash
    env:
      - 'HELM_PLUGINS=/home/ci/.local/share/helm/plugins-new'
    args:
      - -c
      - |
        go run ./cmd/unit-tests                 \
          -target "$_BASE_BRANCH"               \
          -bucket test-logs                     \
          -build "$BUILD_ID"                    \
          -key-secret "$_GITHUB_DEPLOY_KEY_SRC" \
          -a "test-logs/*.json"
    timeout: 25m
