{{- $proxy := mustMergeOverwrite .Values .Values.proxy -}}
{{- $configTemplate := printf "teleport-cluster.proxy.config.%s" $proxy.chartMode -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-proxy
  namespace: {{ .Release.Namespace }}
{{- if $proxy.annotations.config }}
  annotations: {{- toYaml $proxy.annotations.config | nindent 4 }}
{{- end }}
data:
  teleport.yaml: |2
    {{- mustMergeOverwrite (include $configTemplate . | fromYaml) $proxy.teleportConfig | toYaml | nindent 4 -}}
