# This workflow is required to ensure that required Github check passes even if
# the actual "Build on Windows" workflow skipped due to path filtering. Otherwise
# it will stay forever pending.
#
# See "Handling skipped but required checks" for more info:
#
# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
#
# Note both workflows must have the same name.

name: Build on Windows
run-name: Skip Build on Windows

on:
  pull_request:
    # We only build tsh on Windows so only consider Go code as tsh doesn't
    # run any Rust.
    paths-ignore:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'build.assets/Makefile'
      - 'build.assets/Dockerfile*'
  merge_group:
    # We only build tsh on Windows so only consider Go code as tsh doesn't
    # run any Rust.
    paths-ignore:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'build.assets/Makefile'
      - 'build.assets/Dockerfile*'

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    permissions:
      contents: none

    steps:
      - run: 'echo "No code changes"'
